logstash:
  host: "localhost:5000"

spring:
  cloud:
    bus:
      enabled: false
    config:
      enabled: false

  config:
    server:
      bootstrap: false

    consul:
      discovery:
        enabled: false